### ISSUE TITLE
Which options did you use to created the example pictures?

### ISSUE THREAD

**Issue by xiconfjs** [rbart/buddhabrot#1]
Hi @rbart,

which options did you use to create the example pictures? Especially the **antibuddhabrot_huge_crop.jpg**

Thanks
xiconfjs

**Comment by rbart** [comment]
Hi @xiconfjs !

It's been a long time now, but I think it was something like:

"pixelWidth"	1920 // these  two are the pixel dimensions of the output
"pixelHeight"	1080
"oversample"	2 // think of this like anti-aliasing
"imgCenterX"	-0.5 // these three define the field-of-view within the complex plane
"imgCenterY"	0
"imgWidth"		3
"maxIterations" 1000000
"maxCycle"		100
"filename"		antibuddhabrot_huge
"fileExt"		png

But it's probably best to start with smaller numbers (which will run much more quickly) until you know you've got the shot you want, then increase, e.g.

"pixelWidth"	400
"pixelHeight"	300
"oversample"	1
"imgCenterX"	-0.5
"imgCenterY"	0
"imgWidth"		3
"maxIterations" 1000
"maxCycle"		50
"filename"		antibuddhabrot_small
"fileExt"		png

Glad to look into it more if you'd like. Happy to know someone out there finds this interesting.

Cheers

**Comment by xiconfjs** [comment]
thanks. 👍
